---
- name: Instalar o PostgreSQL
  become: true
  apt:
    name: postgresql
    state: latest
    update_cache: true

- name: Iniciar o PostgreSQL
  become: true
  service:
    name: postgresql
    state: started
    enabled: true
